# .github/workflows/release.yml
name: Compile and Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      test-mode:
        description: "Compile only"
        required: false
        default: "false"

jobs:
  release:
    name: release ${{ matrix.target }}
    permissions: write-all
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive_ext: tar.gz
            archive_cmd: tar -czvf
          - os: macos-latest
            target: x86_64-apple-darwin
            archive_ext: tar.gz
            archive_cmd: tar -czvf
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            archive_ext: zip
            archive_cmd: powershell Compress-Archive

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt
          target: ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create packaging folder
        run: |
          mkdir package
          cp config.toml package/
          cp target/${{ matrix.target }}/release/${{ github.event.repository.name }}* package/

      - name: Create archive
        id: archive
        shell: bash
        run: |
          STAGE="${{ steps.collect.outputs.stage_dir }}"
          OUT_NAME="${{ github.event.repository.name }}-${{ matrix.target }}.${{ matrix.archive_ext }}"

          if [[ "${{ matrix.archive_ext }}" == "zip" ]]; then
            # Zip with Powershell
            pwsh -Command "Compress-Archive -Path '${STAGE}\\*' -DestinationPath '${OUT_NAME}'"
          else
            # For tar.gz
            tar -czvf "${OUT_NAME}" -C "${STAGE}" .
          fi

          # Export the archive path for later steps
          echo "archive_path=${OUT_NAME}" >> $GITHUB_OUTPUT

      - name: Upload archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target }}
          path: ${{ steps.archive.outputs.archive_path }}
          retention-days: 30

      - name: Attach archive to Release
        if: success() && inputs.test-mode != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" \
            "${{ steps.archive.outputs.archive_path }}" \
            --repo "${{ github.repository }}" \
            --clobber